'use client';

import React, { useEffect } from 'react';
import { theme } from '@/lib/theme';
import type { AiGeneratedPreset } from '@/lib/api/client';

export type SaveUiState = 'idle' | 'saving' | 'saved' | 'error';

export function AiPresetResultCard({
  preset,
  saveState,
  onPreview,
  onSave,
}: {
  preset: AiGeneratedPreset;
  saveState: SaveUiState;
  onPreview: () => void;
  onSave: () => void;
}) {
  const busy = saveState === 'saving';
  const saved = saveState === 'saved';
  const failed = saveState === 'error';

  return (
    <div
      style={{
        marginTop: 10,
        padding: '12px 14px',
        borderRadius: 14,
        border: `1px solid ${theme.colors.border}`,
        backgroundColor: theme.colors.surface,
        maxWidth: '100%',
      }}
    >
      <div
        style={{
          fontWeight: 700,
          fontSize: 15,
          color: theme.colors.textPrimary,
          marginBottom: 4,
        }}
      >
        💪 {preset.name}
      </div>
      <div
        style={{
          fontSize: 12,
          color: theme.colors.textMuted,
          marginBottom: 10,
        }}
      >
        Generated by Alex
      </div>
      <ul
        style={{
          margin: '0 0 12px',
          paddingLeft: 16,
          color: theme.colors.textSecondary,
          fontSize: 13,
          lineHeight: 1.5,
        }}
      >
        {preset.exercises.map((ex, i) => (
          <li key={`${ex.name}-${i}`} style={{ marginBottom: 6 }}>
            <span style={{ color: theme.colors.textPrimary }}>• {ex.name}</span>
            <span style={{ color: theme.colors.textMuted, marginLeft: 8 }}>
              {ex.sets}×{ex.reps}
              {ex.restSeconds > 0 ? `  ${ex.restSeconds}s` : ''}
            </span>
          </li>
        ))}
      </ul>
      {preset.coachNote ? (
        <div
          style={{
            fontSize: 13,
            color: theme.colors.textSecondary,
            marginBottom: 12,
            padding: '8px 10px',
            borderRadius: 8,
            backgroundColor: 'rgba(255,255,255,0.04)',
            border: '1px solid rgba(255,255,255,0.06)',
          }}
        >
          💬 &quot;{preset.coachNote}&quot;
        </div>
      ) : null}
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
        <button
          type="button"
          onClick={onPreview}
          style={{
            padding: '8px 14px',
            borderRadius: 10,
            border: `1px solid ${theme.colors.border}`,
            backgroundColor: theme.colors.card,
            color: theme.colors.textPrimary,
            fontWeight: 700,
            fontSize: 13,
            cursor: 'pointer',
          }}
        >
          👁 Preview
        </button>
        <button
          type="button"
          onClick={onSave}
          disabled={busy || saved}
          style={{
            padding: '8px 14px',
            borderRadius: 10,
            border: `1px solid ${theme.colors.primary}`,
            backgroundColor: theme.colors.surface,
            color: theme.colors.primary,
            fontWeight: 700,
            fontSize: 13,
            cursor: busy || saved ? 'default' : 'pointer',
            opacity: busy ? 0.7 : 1,
          }}
        >
          {saved ? 'Saved! ✓' : busy ? 'Saving…' : '💾 Save Preset'}
        </button>
      </div>
      {failed && (
        <div
          style={{
            marginTop: 8,
            fontSize: 12,
            color: theme.colors.error,
            fontWeight: 600,
          }}
        >
          Save failed, try again
        </div>
      )}
    </div>
  );
}

/** Chat widget loading card (three bars). */
export function PresetLoadingCard() {
  const rows = [
    { label: 'Selecting exercises', delay: 0 },
    { label: 'Calculating sets', delay: 0.15 },
    { label: 'Optimizing rest times', delay: 0.3 },
  ];
  return (
    <div
      style={{
        alignSelf: 'flex-start',
        padding: '14px 16px',
        borderRadius: 14,
        backgroundColor: '#151b21',
        border: '1px solid rgba(255,255,255,0.06)',
        maxWidth: '92%',
      }}
    >
      <div
        style={{
          fontWeight: 700,
          fontSize: 14,
          color: theme.colors.textPrimary,
          marginBottom: 14,
        }}
      >
        🤖 Building your workout...
      </div>
      {rows.map((row) => (
        <div key={row.label} style={{ marginBottom: 10 }}>
          <div
            style={{
              height: 8,
              borderRadius: 4,
              backgroundColor: 'rgba(255,255,255,0.08)',
              overflow: 'hidden',
              marginBottom: 4,
            }}
          >
            <div
              style={{
                height: '100%',
                borderRadius: 4,
                background:
                  'linear-gradient(90deg, rgba(34,197,94,0.85), rgba(21,128,61,0.95))',
                animation: 'nr-ai-preset-bar 1.35s ease-in-out infinite',
                animationDelay: `${row.delay}s`,
              }}
            />
          </div>
          <div style={{ fontSize: 12, color: theme.colors.textMuted }}>{row.label}</div>
        </div>
      ))}
    </div>
  );
}

/** Onboarding: sequential bars + Alex copy. */
export function OnboardingAlexLoadingCard() {
  const rows = [
    { label: 'Selecting exercises', delay: 0 },
    { label: 'Calculating sets', delay: 0.35 },
    { label: 'Optimizing rest times', delay: 0.7 },
  ];
  return (
    <div
      style={{
        padding: '14px 16px',
        borderRadius: 14,
        backgroundColor: '#151b21',
        border: '1px solid rgba(255,255,255,0.06)',
        width: '100%',
        boxSizing: 'border-box',
      }}
    >
      <div
        style={{
          fontWeight: 700,
          fontSize: 14,
          color: theme.colors.textPrimary,
          marginBottom: 14,
        }}
      >
        Alex is building your workout...
      </div>
      {rows.map((row) => (
        <div key={row.label} style={{ marginBottom: 10 }}>
          <div
            style={{
              height: 8,
              borderRadius: 4,
              backgroundColor: 'rgba(255,255,255,0.08)',
              overflow: 'hidden',
              marginBottom: 4,
            }}
          >
            <div
              style={{
                height: '100%',
                width: '100%',
                borderRadius: 4,
                background:
                  'linear-gradient(90deg, rgba(34,197,94,0.85), rgba(21,128,61,0.95))',
                transformOrigin: 'left center',
                animation: 'nr-onb-seq-bar 2.1s ease-in-out infinite',
                animationDelay: `${row.delay}s`,
              }}
            />
          </div>
          <div style={{ fontSize: 12, color: theme.colors.textMuted }}>{row.label}</div>
        </div>
      ))}
      <style>{`
        @keyframes nr-onb-seq-bar {
          0%, 100% { transform: scaleX(0.15); opacity: 0.5; }
          50% { transform: scaleX(1); opacity: 1; }
        }
      `}</style>
    </div>
  );
}

export function AiPresetPreviewSheet({
  preset,
  onClose,
}: {
  preset: AiGeneratedPreset;
  onClose: () => void;
}) {
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', handleKey);
    return () => document.removeEventListener('keydown', handleKey);
  }, [onClose]);

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 12000,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-end',
      }}
    >
      <div
        role="presentation"
        onClick={onClose}
        style={{
          position: 'absolute',
          inset: 0,
          backgroundColor: 'rgba(0,0,0,0.55)',
        }}
      />
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          position: 'relative',
          maxHeight: '78vh',
          overflowY: 'auto',
          backgroundColor: theme.colors.card,
          borderTop: `1px solid ${theme.colors.border}`,
          borderRadius: '16px 16px 0 0',
          padding:
            '16px 16px max(20px, env(safe-area-inset-bottom, 20px))',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 12,
          }}
        >
          <div
            style={{
              fontWeight: 700,
              fontSize: 17,
              color: theme.colors.textPrimary,
            }}
          >
            💪 {preset.name}
          </div>
          <button
            type="button"
            aria-label="Close preview"
            onClick={onClose}
            style={{
              background: 'none',
              border: 'none',
              color: theme.colors.textSecondary,
              fontSize: 22,
              cursor: 'pointer',
              padding: 4,
            }}
          >
            ✕
          </button>
        </div>
        <p
          style={{
            margin: '0 0 12px',
            fontSize: 13,
            color: theme.colors.textMuted,
          }}
        >
          Read-only preview · Generated by Alex
        </p>
        <ol
          style={{
            margin: 0,
            paddingLeft: 18,
            color: theme.colors.textSecondary,
            fontSize: 14,
            lineHeight: 1.55,
          }}
        >
          {preset.exercises.map((ex, i) => (
            <li key={`pv-${i}`} style={{ marginBottom: 8 }}>
              <strong style={{ color: theme.colors.textPrimary }}>
                {ex.name}
              </strong>
              {' — '}
              {ex.sets}×{ex.reps}
              {ex.restSeconds > 0 ? ` · ${ex.restSeconds}s rest` : ''}
            </li>
          ))}
        </ol>
        {preset.coachNote ? (
          <p
            style={{
              margin: '14px 0 0',
              fontSize: 13,
              color: theme.colors.textSecondary,
              lineHeight: 1.45,
            }}
          >
            💬 {preset.coachNote}
          </p>
        ) : null}
      </div>
    </div>
  );
}
